services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rag_db
      - DB_USER=rag_user
      - DB_PASSWORD=rag_password
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - MISTRAL_MODEL=${MISTRAL_MODEL}
      - OPENAI_MODEL=${OPENAI_MODEL}
    volumes:
      - ./docs:/app/docs
    command: ["tail", "-f", "/dev/null"]

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rag_db
      - DB_USER=rag_user
      - DB_PASSWORD=rag_password
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - MISTRAL_MODEL=${MISTRAL_MODEL}
      - OPENAI_MODEL=${OPENAI_MODEL}
    command: ["python", "app.py"]

volumes:
  postgres_data:
